### ISSUE TITLE
not all bolus have recommended amount

### ISSUE THREAD

**Issue by bewest** [tidepool-org/deprecated-data-model#5]
# bolus data should not assume use of wizard

Some people do not use the bolus wizard (many adults do not) eg @skrugman does not.  Also pen and syringe users give bolus injections and injection corrections which map `1:1` with a bolus but with no recommended amount because it's not a wizard.
- [ ] data model should model insulin-use
- [ ] one type of insulin use should reflect wizard usage with `recommended`
- [ ] one type of insulin use should reflect bolus without wizard usage, sans `recommended`

As a side-effect of structuring the work this way, blip will be that much more prepared to and MDI usage as well.

**Comment by jebeck** [comment]
OK, fair enough, but can you propose a concrete JSON that we can discuss?

**Comment by brandonarbiter** [comment]
We have proposed JSON style data model in this doc (https://docs.google.com/a/tidepool.org/document/d/1S04g5t_NGs63O6lnJ6eoBJDwt-NESqON8A_EY-Rew9c/edit) and I think in the Wiki. When bolus wizard is not used, carb input should just be left blank, right?

Date
Time
Carb Input
Carb Ratio
Insulin Recommendation for Carbs
BG Input
BG Source (Automated, Human)
Sensitivity
Insulin Recommendation for Correction
Total Insulin Recommendation
Insulin Dosage Amount
Extended Bolus Type
Extended Bolus Duration
Type (Pump, Manual)
Id
Make
Model

**Comment by jebeck** [comment]
@brandonarbiter I transferred that doc to the wiki a while ago and it is now outdated. Can we forget it exists, please? ;) Google Docs is not a good place for hosting documentation.

By proposed JSON I mean actual JSON - including data structure and attribute names since the viz code references these directly and they have to agree exactly with what comes out of the back end.

@bewest After thinking about this some more, I'm actually not sure why you entered this issue. What's wrong with just having a `null` value for the pieces of data that won't be there when the bolus wizard is not used?

Or are you proposing that we also identify sub-types for boluses (i.e., pump-wizard, pump-manual, injection)? From the pump data I think the pump-wizard vs. pump-manual distinction would just be redundant - we'd be able to tell which is which by whether 'recommended' has a value or is null. But I can see a justification for sub-typing (but I'll argue for keeping the macro `'type': 'bolus'` property) waaaaay down the road if we offer a way for all patients to enter in injection logs...we might want to help a pump user identify when they took an injection instead of using the pump (something one is often advised to do when you suspect your infusion site is bad, for example).

**Comment by bewest** [comment]
This issue is not about json for visualization, there is no proposal to change it.  It is about how to validate that a given record is correct, and being able to correctly disambiguate it and validate it separately from other types of records.

Right now, it's hard to validate whether or not bolus records are correct or not, I'm after stricter set of rules with which to verify that a parser is doing the correct thing.  If it's allowed to sometimes do finicky things, it's that much harder to validate, that's all.  This issue is for me to take notes, not for the UCSF pilot.  There will be many more like it, not all of them need to be solved immediately.

So yes, eventually, not today or next week, I imagine we'll have base and core types from which everything subclasses/inherits.  For bolus and basal that base type will probably be 'insulin-use', subclasses for pump vs syringe, and further subclassing to derive "normal" bolus vs "dual" vs "square" vs custom "extended/combo".  This will allow our robots/tests/app/QA/people to validate that all parsers (and everything else) is behaving as expected.  Right now a validator using json-schema cannot tell the difference between a valid vs invalid dual or square of combination record, even when it is invalid.

That's fine for short term, but not long term, hence the issue so I can track this later.

If it would help I can enable some tests to show what's failing more visibly, but I don't think that would be valuable, a few issues seem like the right way to track things for backlog and long term discussion.

I'm not proposing any specific solutions right now because I don't expect us to necessarily solve it immediately.

**Comment by jebeck** [comment]
So are you against specifying `recommended` and other such attributes as optional in the schema, assuming that's possible? That seems like the obvious solution, and also an accurate representation of reality.
